-- MySQL Script generated by MySQL Workbench
-- Thu Oct 26 21:25:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema graduate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema graduate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `graduate` DEFAULT CHARACTER SET utf8 ;
USE `graduate` ;

-- -----------------------------------------------------
-- Table `graduate`.`hinhthuc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`hinhthuc` (
  `MA_HINHTHUC` INT(11) NOT NULL AUTO_INCREMENT,
  `TEN_HINHTHUC` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`MA_HINHTHUC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`khachhang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`khachhang` (
  `MA_KHACHHANG` INT(11) NOT NULL AUTO_INCREMENT,
  `HO` VARCHAR(100) NULL DEFAULT NULL,
  `TEN` VARCHAR(45) NULL DEFAULT NULL,
  `SDT` VARCHAR(20) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `DIACHI` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `MATKHAU` VARCHAR(45) NULL DEFAULT NULL,
  `TRANGTHAI` INT(11) NOT NULL DEFAULT '1',
  `NGAY_TAO` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `GIOITINH` TINYINT NULL DEFAULT 0,
  `NGAYSINH` DATE NULL DEFAULT NULL,
  `DIEMTHUONG` INT NULL DEFAULT 0,
  PRIMARY KEY (`MA_KHACHHANG`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`chucvu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`chucvu` (
  `MA_CHUCVU` INT(11) NOT NULL AUTO_INCREMENT,
  `TEN_CHUCVU` VARCHAR(45) NULL DEFAULT NULL,
  `CAPBAC_LUONG` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`MA_CHUCVU`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`nhanvien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`nhanvien` (
  `MA_NHANVIEN` INT(11) NOT NULL AUTO_INCREMENT,
  `HO` VARCHAR(100) NULL DEFAULT NULL,
  `TEN` VARCHAR(45) NULL DEFAULT NULL,
  `MATKHAU` VARCHAR(45) NULL DEFAULT NULL,
  `SDT` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `DIACHI` TEXT NOT NULL,
  `NGAYSINH` DATE NULL DEFAULT NULL,
  `HINHANH` VARCHAR(100) NULL DEFAULT NULL,
  `GIOITINH` TINYINT(4) NULL DEFAULT NULL,
  `NGAY_TAO` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MA_CHUCVU` INT(11) NOT NULL,
  `TRANGTHAI` TINYINT(4) NULL DEFAULT '1',
  PRIMARY KEY USING BTREE (`MA_NHANVIEN`),
  INDEX `fk_nhanvien_chucvu1_idx` (`MA_CHUCVU` ASC),
  CONSTRAINT `fk_nhanvien_chucvu1`
    FOREIGN KEY (`MA_CHUCVU`)
    REFERENCES `graduate`.`chucvu` (`MA_CHUCVU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`giaodich`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`giaodich` (
  `MA_GIAODICH` INT(11) NOT NULL AUTO_INCREMENT,
  `TONG_THANHTIEN` INT(11) NULL DEFAULT NULL,
  `DIACHI_GIAO` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `TRANGTHAI` TINYINT(4) NULL DEFAULT '0',
  `NGAY_GIAODICH` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `NGAYLAP_HOADON` DATE NULL DEFAULT NULL,
  `MA_KHACHHANG` INT(11) NOT NULL,
  `MA_HINHTHUC` INT(11) NOT NULL,
  `MA_NHANVIEN` INT(11) NOT NULL,
  PRIMARY KEY USING BTREE (`MA_GIAODICH`),
  INDEX `fk_giaodich_khachhang1_idx` (`MA_KHACHHANG` ASC),
  INDEX `fk_giaodich_hinhthuc1_idx` (`MA_HINHTHUC` ASC),
  INDEX `fk_giaodich_nhanvien` (`MA_NHANVIEN` ASC),
  CONSTRAINT `fk_giaodich_hinhthuc1`
    FOREIGN KEY (`MA_HINHTHUC`)
    REFERENCES `graduate`.`hinhthuc` (`MA_HINHTHUC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_giaodich_khachhang1`
    FOREIGN KEY (`MA_KHACHHANG`)
    REFERENCES `graduate`.`khachhang` (`MA_KHACHHANG`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_giaodich_nhanvien`
    FOREIGN KEY (`MA_NHANVIEN`)
    REFERENCES `graduate`.`nhanvien` (`MA_NHANVIEN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`nha_cungcap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`nha_cungcap` (
  `MA_NHA_CUNGCAP` INT(11) NOT NULL AUTO_INCREMENT,
  `TEN_NHA_CUNGCAP` VARCHAR(100) NULL DEFAULT NULL,
  `WEBSITE` VARCHAR(255) NOT NULL,
  `DIACHI_NHA_CUNGCAP` TEXT NULL DEFAULT NULL,
  `SDT` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `TRANGTHAI` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`MA_NHA_CUNGCAP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`thuonghieu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`thuonghieu` (
  `MA_THUONGHIEU` INT(11) NOT NULL AUTO_INCREMENT,
  `TEN_THUONGHIEU` VARCHAR(50) NULL DEFAULT NULL,
  `LOGO` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`MA_THUONGHIEU`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`loai_sanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`loai_sanpham` (
  `MA_LOAI_SANPHAM` INT(11) NOT NULL AUTO_INCREMENT,
  `TEN_LOAI_SANPHAM` VARCHAR(50) NULL DEFAULT NULL,
  `MA_NHA_CUNGCAP` INT(11) NOT NULL,
  `MA_THUONGHIEU` INT(11) NOT NULL,
  PRIMARY KEY USING BTREE (`MA_LOAI_SANPHAM`),
  INDEX `ma_nha_cungcap` (`MA_NHA_CUNGCAP` ASC),
  INDEX `fk_loai_sanpham_thuonghieu1_idx` (`MA_THUONGHIEU` ASC),
  CONSTRAINT `ma_nha_cungcap`
    FOREIGN KEY (`MA_NHA_CUNGCAP`)
    REFERENCES `graduate`.`nha_cungcap` (`MA_NHA_CUNGCAP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_loai_sanpham_thuonghieu1`
    FOREIGN KEY (`MA_THUONGHIEU`)
    REFERENCES `graduate`.`thuonghieu` (`MA_THUONGHIEU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`xuatxu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`xuatxu` (
  `MA_XUATXU` INT(11) NOT NULL AUTO_INCREMENT,
  `TEN_XUATXU` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`MA_XUATXU`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`kho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`kho` (
  `MA_KHO` INT(11) NOT NULL AUTO_INCREMENT,
  `TEN_KHO` VARCHAR(100) NULL DEFAULT NULL,
  `SOLUONG_TON` INT(11) NULL DEFAULT '0',
  `VITRI` VARCHAR(45) NULL,
  `MA_NHANVIEN` INT(11) NOT NULL,
  PRIMARY KEY USING BTREE (`MA_KHO`, `MA_NHANVIEN`),
  INDEX `fk_kho_nhanvien1_idx` (`MA_NHANVIEN` ASC),
  CONSTRAINT `fk_kho_nhanvien1`
    FOREIGN KEY (`MA_NHANVIEN`)
    REFERENCES `graduate`.`nhanvien` (`MA_NHANVIEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`chitiet_kho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`chitiet_kho` (
  `MA_LOAI_SANPHAM` INT(11) NOT NULL,
  `MA_KHO` INT(11) NOT NULL,
  `SOLUONG_TON` INT NULL COMMENT 'Để cho biết sức chứa của kho hiện tại là bao nhiêu (tổng các sản phẩm nhiều loại trong 1 kho)',
  `TEN_SANPHAM` VARCHAR(255) NULL,
  `DONGIA_BAN` INT NULL,
  `HINH_DAIDIEN` VARCHAR(255) NULL,
  `THOIGIAN_BH` TINYINT(4) NULL,
  `SOLUONG` INT NULL,
  `NGAY_CAPNHAT` DATE NULL,
  `MOTA` TEXT NULL,
  `TRANGTHAI` TINYINT(4) NULL,
  `LUOTXEM` INT NULL,
  `MA_XUATXU` INT(11) NOT NULL,
  PRIMARY KEY (`MA_LOAI_SANPHAM`, `MA_KHO`),
  INDEX `fk_chitiet_kho_xuatxu1_idx` (`MA_XUATXU` ASC),
  INDEX `fk_chitiet_kho_loai_sanpham1_idx` (`MA_LOAI_SANPHAM` ASC),
  INDEX `fk_chitiet_kho_kho1_idx` (`MA_KHO` ASC),
  CONSTRAINT `fk_chitiet_kho_xuatxu1`
    FOREIGN KEY (`MA_XUATXU`)
    REFERENCES `graduate`.`xuatxu` (`MA_XUATXU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chitiet_kho_loai_sanpham1`
    FOREIGN KEY (`MA_LOAI_SANPHAM`)
    REFERENCES `graduate`.`loai_sanpham` (`MA_LOAI_SANPHAM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chitiet_kho_kho1`
    FOREIGN KEY (`MA_KHO`)
    REFERENCES `graduate`.`kho` (`MA_KHO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graduate`.`sanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`sanpham` (
  `MA_SANPHAM` INT(11) NOT NULL AUTO_INCREMENT,
  `MA_LOAI_SANPHAM` INT(11) NOT NULL,
  `MA_KHO` INT(11) NOT NULL,
  PRIMARY KEY USING BTREE (`MA_SANPHAM`, `MA_LOAI_SANPHAM`, `MA_KHO`),
  INDEX `fk_sanpham_chitiet_kho1_idx` (`MA_LOAI_SANPHAM` ASC, `MA_KHO` ASC),
  CONSTRAINT `fk_sanpham_chitiet_kho1`
    FOREIGN KEY (`MA_LOAI_SANPHAM` , `MA_KHO`)
    REFERENCES `graduate`.`chitiet_kho` (`MA_LOAI_SANPHAM` , `MA_KHO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `graduate`.`chitiet_giaodich`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`chitiet_giaodich` (
  `MA_GIAODICH` INT(11) NOT NULL,
  `MA_SANPHAM` INT(11) NOT NULL,
  `MA_LOAI_SANPHAM` INT(11) NOT NULL,
  `MA_KHO` INT(11) NOT NULL,
  `SOLUONG` INT(11) NOT NULL,
  `THANHTIEN` INT(11) NOT NULL,
  `THANHTOAN` INT(11) NOT NULL,
  `TRANGTHAI` TINYINT(6) NOT NULL DEFAULT '0',
  INDEX `fk_chitiet_giaodich_giaodich1_idx` (`MA_GIAODICH` ASC),
  PRIMARY KEY (`MA_GIAODICH`, `MA_SANPHAM`, `MA_LOAI_SANPHAM`, `MA_KHO`),
  INDEX `fk_chitiet_giaodich_sanpham1_idx` (`MA_SANPHAM` ASC, `MA_LOAI_SANPHAM` ASC, `MA_KHO` ASC),
  CONSTRAINT `fk_chitiet_giaodich_giaodich1`
    FOREIGN KEY (`MA_GIAODICH`)
    REFERENCES `graduate`.`giaodich` (`MA_GIAODICH`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chitiet_giaodich_sanpham1`
    FOREIGN KEY (`MA_SANPHAM` , `MA_LOAI_SANPHAM` , `MA_KHO`)
    REFERENCES `graduate`.`sanpham` (`MA_SANPHAM` , `MA_LOAI_SANPHAM` , `MA_KHO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`khuyenmai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`khuyenmai` (
  `MA_KHUYENMAI` INT(11) NOT NULL AUTO_INCREMENT,
  `TEN_KHUYENMAI` VARCHAR(100) NULL DEFAULT NULL,
  `NGAY_BATDAU` DATE NULL DEFAULT NULL,
  `NGAY_KETTHUC` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`MA_KHUYENMAI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`chitiet_khuyenmai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`chitiet_khuyenmai` (
  `MA_KHUYENMAI` INT(11) NOT NULL,
  `MA_LOAI_SANPHAM` INT(11) NOT NULL,
  `MA_KHO` INT(11) NOT NULL,
  `PHANTRAM_KM` INT(11) NULL DEFAULT NULL,
  `TANGPHAM` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`MA_KHUYENMAI`, `MA_LOAI_SANPHAM`, `MA_KHO`),
  INDEX `fk_chitiet_khuyenmai_khuyenmai1_idx` (`MA_KHUYENMAI` ASC),
  INDEX `fk_chitiet_khuyenmai_chitiet_kho1_idx` (`MA_LOAI_SANPHAM` ASC, `MA_KHO` ASC),
  CONSTRAINT `fk_chitiet_khuyenmai_khuyenmai1`
    FOREIGN KEY (`MA_KHUYENMAI`)
    REFERENCES `graduate`.`khuyenmai` (`MA_KHUYENMAI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chitiet_khuyenmai_chitiet_kho1`
    FOREIGN KEY (`MA_LOAI_SANPHAM` , `MA_KHO`)
    REFERENCES `graduate`.`chitiet_kho` (`MA_LOAI_SANPHAM` , `MA_KHO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`phieunhap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`phieunhap` (
  `MA_PHIEUNHAP` INT(11) NOT NULL AUTO_INCREMENT,
  `NGAYLAP_PHIEUNHAP` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TONG_THANHTIEN` INT(11) NOT NULL DEFAULT 0,
  `MA_NHA_CUNGCAP` INT(11) NOT NULL,
  `TIEN_TRATRUOC` INT NULL DEFAULT 0,
  `TRANGTHAI` TINYINT NULL DEFAULT NULL,
  `MA_NHANVIEN` INT(11) NOT NULL,
  PRIMARY KEY USING BTREE (`MA_PHIEUNHAP`),
  INDEX `fk_phieunhap_nha_cungcap1_idx` (`MA_NHA_CUNGCAP` ASC),
  INDEX `fk_phieunhap_nhanvien1_idx` (`MA_NHANVIEN` ASC),
  CONSTRAINT `fk_phieunhap_nha_cungcap1`
    FOREIGN KEY (`MA_NHA_CUNGCAP`)
    REFERENCES `graduate`.`nha_cungcap` (`MA_NHA_CUNGCAP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phieunhap_nhanvien1`
    FOREIGN KEY (`MA_NHANVIEN`)
    REFERENCES `graduate`.`nhanvien` (`MA_NHANVIEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`chitiet_nhap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`chitiet_nhap` (
  `MA_PHIEUNHAP` INT(11) NOT NULL,
  `MA_LOAI_SANPHAM` INT(11) NOT NULL,
  `MA_KHO` INT(11) NOT NULL,
  `SOLUONGNHAP` INT(11) NOT NULL,
  `DONGIA_NHAP` INT(11) NULL DEFAULT NULL,
  `THANHTIEN` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`MA_PHIEUNHAP`, `MA_LOAI_SANPHAM`, `MA_KHO`),
  INDEX `MA_PHIEUNHAP` (`MA_PHIEUNHAP` ASC),
  INDEX `fk_chitiet_nhap_chitiet_kho1_idx` (`MA_LOAI_SANPHAM` ASC, `MA_KHO` ASC),
  CONSTRAINT `fk_chitiet_phieunhap_phieunhap`
    FOREIGN KEY (`MA_PHIEUNHAP`)
    REFERENCES `graduate`.`phieunhap` (`MA_PHIEUNHAP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chitiet_nhap_chitiet_kho1`
    FOREIGN KEY (`MA_LOAI_SANPHAM` , `MA_KHO`)
    REFERENCES `graduate`.`chitiet_kho` (`MA_LOAI_SANPHAM` , `MA_KHO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`dacdiem_kythuat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`dacdiem_kythuat` (
  `MA_LOAI_SANPHAM` INT(11) NOT NULL,
  `MA_KHO` INT(11) NOT NULL,
  `MAU_SAC` VARCHAR(100) NULL DEFAULT NULL,
  `KHOILUONG` INT(11) NULL DEFAULT NULL,
  `KICH_THUOC` VARCHAR(50) NULL DEFAULT NULL,
  `CHATLIEU` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`MA_LOAI_SANPHAM`, `MA_KHO`),
  CONSTRAINT `fk_dacdiem_kythuat_chitiet_kho1`
    FOREIGN KEY (`MA_LOAI_SANPHAM` , `MA_KHO`)
    REFERENCES `graduate`.`chitiet_kho` (`MA_LOAI_SANPHAM` , `MA_KHO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `graduate`.`baohanh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`baohanh` (
  `MA_GIAODICH` INT(11) NOT NULL,
  `MA_SANPHAM` INT(11) NOT NULL,
  `MA_LOAI_SANPHAM` INT(11) NOT NULL,
  `MA_KHO` INT(11) NOT NULL,
  `LAN_BAOHANH` INT NULL DEFAULT 0,
  `NGAY_TIEPNHAN` DATE NULL DEFAULT NULL,
  `NOIDUNG_BH` TEXT NULL DEFAULT NULL,
  `PHI_BH` INT NULL DEFAULT NULL,
  `GHICHU` VARCHAR(45) NULL DEFAULT NULL,
  `TINHTRANG` INT NULL DEFAULT 0,
  `NGAY_HENTRA` DATE NULL,
  `NGAY_TRA` DATE NULL,
  `MA_NHANVIEN` INT(11) NOT NULL,
  PRIMARY KEY (`MA_GIAODICH`, `MA_SANPHAM`, `MA_LOAI_SANPHAM`, `MA_KHO`),
  INDEX `fk_baohanh_nhanvien1_idx` (`MA_NHANVIEN` ASC),
  INDEX `fk_baohanh_chitiet_giaodich2_idx` (`MA_GIAODICH` ASC, `MA_SANPHAM` ASC, `MA_LOAI_SANPHAM` ASC, `MA_KHO` ASC),
  CONSTRAINT `fk_baohanh_nhanvien1`
    FOREIGN KEY (`MA_NHANVIEN`)
    REFERENCES `graduate`.`nhanvien` (`MA_NHANVIEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_baohanh_chitiet_giaodich2`
    FOREIGN KEY (`MA_GIAODICH` , `MA_SANPHAM` , `MA_LOAI_SANPHAM` , `MA_KHO`)
    REFERENCES `graduate`.`chitiet_giaodich` (`MA_GIAODICH` , `MA_SANPHAM` , `MA_LOAI_SANPHAM` , `MA_KHO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graduate`.`gop_y`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graduate`.`gop_y` (
  `MA_GOPY` INT NOT NULL AUTO_INCREMENT,
  `MA_KHACHHANG` INT(11) NOT NULL,
  `MA_NHANVIEN` INT(11) NOT NULL,
  `ND_GOPY` TEXT NULL,
  `ND_TRALOI` TEXT NULL,
  `NGAY_GOPY` DATE NULL,
  `NGAY_TRALOI` DATE NULL,
  PRIMARY KEY (`MA_GOPY`, `MA_KHACHHANG`, `MA_NHANVIEN`),
  INDEX `fk_gop_y_khachhang1_idx` (`MA_KHACHHANG` ASC),
  INDEX `fk_gop_y_nhanvien1_idx` (`MA_NHANVIEN` ASC),
  CONSTRAINT `fk_gop_y_khachhang1`
    FOREIGN KEY (`MA_KHACHHANG`)
    REFERENCES `graduate`.`khachhang` (`MA_KHACHHANG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gop_y_nhanvien1`
    FOREIGN KEY (`MA_NHANVIEN`)
    REFERENCES `graduate`.`nhanvien` (`MA_NHANVIEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `graduate`;

DELIMITER $$
USE `graduate`$$
CREATE TRIGGER `THANH_TIEN` BEFORE INSERT ON `chitiet_nhap` FOR EACH ROW BEGIN
  DECLARE MA_LOAISP INT; 
  DECLARE TONG_TT INT;
 SET NEW.THANHTIEN = NEW.SOLUONGNHAP * NEW.DONGIA_NHAP;


 SET @MA_LOAISP = (SELECT MA_LOAI_SANPHAM FROM sanpham 
                  WHERE MA_SANPHAM = NEW.MA_SANPHAM);

UPDATE kho SET SOLUONG_TON =SOLUONG_TON + NEW.SOLUONGNHAP
WHERE MA_LOAI_SANPHAM = @MA_LOAISP; 

 SET @TONG_TT = (SELECT SUM(THANHTIEN) FROM chitiet_nhap 						WHERE MA_PHIEUNHAP = NEW.MA_PHIEUNHAP);
 UPDATE phieunhap SET TONG_THANHTIEN = @TONG_TT
 					WHERE MA_PHIEUNHAP = NEW.MA_PHIEUNHAP;
 UPDATE sanpham 
 SET SOLUONG_BAN =SOLUONG_BAN + NEW.SOLUONGNHAP
 					WHERE MA_SANPHAM = NEW.MA_SANPHAM;

END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
